packages:
  - "packages/api"
  - "packages/core"
  - "packages/db"
  - "packages/llm"
  - "packages/local-agent"
  - "packages/store"
  - "packages/types"
  - "apps/cli"
  - "apps/desktop"
  - "apps/mcp"
confirmModulesPurge: false
allowBuilds:
  '@swc/core': true
  electron: true
  electron-winstaller: true
  esbuild: true
  sharp: true
  workerd: true
overrides:
  react: 19.2.7
  react-dom: 19.2.7
