/**
 * Generated by the Supabase MCP `generate_typescript_types` against the live
 * aimcub project (ref gtasruxwmcsxicyujlfu, us-west-1) — regenerated after
 * migration 0011 dropped the emotional shell (pets / collectibles / notifications,
 * the rarity / minted_collectible_id columns, and the upsert_pet_monotonic RPC).
 * Reference artifact: the source of truth for union values stays @core/types
 * (zod); DB enums are text + CHECK by design.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      activity_pings: {
        Row: {
          created_at: string
          day: string
          owner_id: string
        }
        Insert: {
          created_at?: string
          day: string
          owner_id: string
        }
        Update: {
          created_at?: string
          day?: string
          owner_id?: string
        }
        Relationships: []
      }
      auth_client_audiences: {
        Row: {
          audience: string
          client_id: string
          created_at: string
          note: string
        }
        Insert: {
          audience: string
          client_id: string
          created_at?: string
          note?: string
        }
        Update: {
          audience?: string
          client_id?: string
          created_at?: string
          note?: string
        }
        Relationships: []
      }
      emitters: {
        Row: {
          created_at: string
          display_name: string
          id: string
          kind: string
          owner_id: string
          revoked_at: string | null
          token_hash: string | null
        }
        Insert: {
          created_at?: string
          display_name?: string
          id?: string
          kind: string
          owner_id: string
          revoked_at?: string | null
          token_hash?: string | null
        }
        Update: {
          created_at?: string
          display_name?: string
          id?: string
          kind?: string
          owner_id?: string
          revoked_at?: string | null
          token_hash?: string | null
        }
        Relationships: []
      }
      evidence: {
        Row: {
          created_at: string
          emitter_id: string | null
          goal_id: string
          id: string
          kind: string
          milestone_id: string | null
          occurred_at: string
          owner_id: string
          payload: Json
          source_event_id: string | null
          summary: string
          trust_score: number
        }
        Insert: {
          created_at?: string
          emitter_id?: string | null
          goal_id: string
          id?: string
          kind: string
          milestone_id?: string | null
          occurred_at: string
          owner_id: string
          payload?: Json
          source_event_id?: string | null
          summary?: string
          trust_score?: number
        }
        Update: {
          created_at?: string
          emitter_id?: string | null
          goal_id?: string
          id?: string
          kind?: string
          milestone_id?: string | null
          occurred_at?: string
          owner_id?: string
          payload?: Json
          source_event_id?: string | null
          summary?: string
          trust_score?: number
        }
        Relationships: [
          {
            foreignKeyName: "evidence_emitter_id_fkey"
            columns: ["emitter_id"]
            isOneToOne: false
            referencedRelation: "emitters"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "evidence_goal_id_fkey"
            columns: ["goal_id"]
            isOneToOne: false
            referencedRelation: "goals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "evidence_milestone_id_fkey"
            columns: ["milestone_id"]
            isOneToOne: false
            referencedRelation: "milestones"
            referencedColumns: ["id"]
          },
        ]
      }
      goals: {
        Row: {
          created_at: string
          description: string
          domain: string
          id: string
          metadata: Json
          owner_id: string
          plan_json: Json | null
          status: string
          target_date: string | null
          title: string
        }
        Insert: {
          created_at?: string
          description?: string
          domain?: string
          id?: string
          metadata?: Json
          owner_id: string
          plan_json?: Json | null
          status?: string
          target_date?: string | null
          title: string
        }
        Update: {
          created_at?: string
          description?: string
          domain?: string
          id?: string
          metadata?: Json
          owner_id?: string
          plan_json?: Json | null
          status?: string
          target_date?: string | null
          title?: string
        }
        Relationships: []
      }
      jobs: {
        Row: {
          attempts: number
          claimed_at: string | null
          created_at: string
          dedup_key: string | null
          id: string
          last_error: string | null
          payload: Json
          run_after: string
          status: string
          type: string
        }
        Insert: {
          attempts?: number
          claimed_at?: string | null
          created_at?: string
          dedup_key?: string | null
          id?: string
          last_error?: string | null
          payload?: Json
          run_after?: string
          status?: string
          type: string
        }
        Update: {
          attempts?: number
          claimed_at?: string | null
          created_at?: string
          dedup_key?: string | null
          id?: string
          last_error?: string | null
          payload?: Json
          run_after?: string
          status?: string
          type?: string
        }
        Relationships: []
      }
      memories: {
        Row: {
          confidence: number
          content: string
          created_at: string
          goal_id: string | null
          id: string
          kind: string
          owner_id: string
          source: string
          status: string
          superseded_by: string | null
        }
        Insert: {
          confidence?: number
          content: string
          created_at?: string
          goal_id?: string | null
          id?: string
          kind: string
          owner_id: string
          source?: string
          status?: string
          superseded_by?: string | null
        }
        Update: {
          confidence?: number
          content?: string
          created_at?: string
          goal_id?: string | null
          id?: string
          kind?: string
          owner_id?: string
          source?: string
          status?: string
          superseded_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "memories_goal_id_fkey"
            columns: ["goal_id"]
            isOneToOne: false
            referencedRelation: "goals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "memories_superseded_by_fkey"
            columns: ["superseded_by"]
            isOneToOne: false
            referencedRelation: "memories"
            referencedColumns: ["id"]
          },
        ]
      }
      milestone_completions: {
        Row: {
          awarded_xp: number
          created_at: string
          decided_by: string
          id: string
          milestone_id: string
          owner_id: string
          triggering_evidence_ids: string[]
        }
        Insert: {
          awarded_xp?: number
          created_at?: string
          decided_by: string
          id?: string
          milestone_id: string
          owner_id: string
          triggering_evidence_ids?: string[]
        }
        Update: {
          awarded_xp?: number
          created_at?: string
          decided_by?: string
          id?: string
          milestone_id?: string
          owner_id?: string
          triggering_evidence_ids?: string[]
        }
        Relationships: [
          {
            foreignKeyName: "milestone_completions_milestone_id_fkey"
            columns: ["milestone_id"]
            isOneToOne: true
            referencedRelation: "milestones"
            referencedColumns: ["id"]
          },
        ]
      }
      milestones: {
        Row: {
          acceptance_rule: Json
          completed_at: string | null
          created_at: string
          depends_on_id: string | null
          description: string
          goal_id: string
          id: string
          metadata: Json
          order_index: number
          owner_id: string
          status: string
          title: string
          xp_reward: number
        }
        Insert: {
          acceptance_rule?: Json
          completed_at?: string | null
          created_at?: string
          depends_on_id?: string | null
          description?: string
          goal_id: string
          id?: string
          metadata?: Json
          order_index?: number
          owner_id: string
          status?: string
          title: string
          xp_reward?: number
        }
        Update: {
          acceptance_rule?: Json
          completed_at?: string | null
          created_at?: string
          depends_on_id?: string | null
          description?: string
          goal_id?: string
          id?: string
          metadata?: Json
          order_index?: number
          owner_id?: string
          status?: string
          title?: string
          xp_reward?: number
        }
        Relationships: [
          {
            foreignKeyName: "milestones_depends_on_id_fkey"
            columns: ["depends_on_id"]
            isOneToOne: false
            referencedRelation: "milestones"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "milestones_goal_id_fkey"
            columns: ["goal_id"]
            isOneToOne: false
            referencedRelation: "goals"
            referencedColumns: ["id"]
          },
        ]
      }
      subscriptions: {
        Row: {
          expires_at: string | null
          owner_id: string
          source: string
          tier: string
        }
        Insert: {
          expires_at?: string | null
          owner_id: string
          source: string
          tier?: string
        }
        Update: {
          expires_at?: string | null
          owner_id?: string
          source?: string
          tier?: string
        }
        Relationships: []
      }
    }
    Views: {
      weekly_active: {
        Row: {
          active_owners: number | null
          week_start: string | null
        }
        Relationships: []
      }
      wmcu_weekly: {
        Row: {
          active_owners: number | null
          week_start: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      claim_jobs: {
        Args: { batch?: number }
        Returns: {
          attempts: number
          claimed_at: string | null
          created_at: string
          dedup_key: string | null
          id: string
          last_error: string | null
          payload: Json
          run_after: string
          status: string
          type: string
        }[]
        SetofOptions: {
          from: "*"
          to: "jobs"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      custom_access_token: { Args: { event: Json }; Returns: Json }
      get_app_secret: { Args: { secret_name: string }; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
