/**
 * Generated by the Supabase MCP `generate_typescript_types` against the live
 * aimcub project (ref gtasruxwmcsxicyujlfu, us-west-1) — 2026-06-10, after
 * migrations 0001-0003. Reference artifact: the source of truth for union
 * values stays @core/types (zod); DB enums are text + CHECK by design.
 * Regenerate after every applied migration.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      collectibles: {
        Row: {
          goal_id: string | null;
          id: string;
          image_url: string | null;
          kind: string;
          metadata: Json;
          milestone_id: string | null;
          minted_at: string;
          owner_id: string;
          rarity: string;
        };
        Insert: {
          goal_id?: string | null;
          id?: string;
          image_url?: string | null;
          kind?: string;
          metadata?: Json;
          milestone_id?: string | null;
          minted_at?: string;
          owner_id: string;
          rarity: string;
        };
        Update: {
          goal_id?: string | null;
          id?: string;
          image_url?: string | null;
          kind?: string;
          metadata?: Json;
          milestone_id?: string | null;
          minted_at?: string;
          owner_id?: string;
          rarity?: string;
        };
      };
      emitters: {
        Row: {
          created_at: string;
          display_name: string;
          id: string;
          kind: string;
          owner_id: string;
          revoked_at: string | null;
          token_hash: string | null;
        };
        Insert: {
          created_at?: string;
          display_name?: string;
          id?: string;
          kind: string;
          owner_id: string;
          revoked_at?: string | null;
          token_hash?: string | null;
        };
        Update: {
          created_at?: string;
          display_name?: string;
          id?: string;
          kind?: string;
          owner_id?: string;
          revoked_at?: string | null;
          token_hash?: string | null;
        };
      };
      evidence: {
        Row: {
          created_at: string;
          emitter_id: string | null;
          goal_id: string;
          id: string;
          kind: string;
          milestone_id: string | null;
          occurred_at: string;
          owner_id: string;
          payload: Json;
          source_event_id: string | null;
          summary: string;
          trust_score: number;
        };
        Insert: {
          created_at?: string;
          emitter_id?: string | null;
          goal_id: string;
          id?: string;
          kind: string;
          milestone_id?: string | null;
          occurred_at: string;
          owner_id: string;
          payload?: Json;
          source_event_id?: string | null;
          summary?: string;
          trust_score?: number;
        };
        Update: {
          created_at?: string;
          emitter_id?: string | null;
          goal_id?: string;
          id?: string;
          kind?: string;
          milestone_id?: string | null;
          occurred_at?: string;
          owner_id?: string;
          payload?: Json;
          source_event_id?: string | null;
          summary?: string;
          trust_score?: number;
        };
      };
      goals: {
        Row: {
          created_at: string;
          description: string;
          domain: string;
          id: string;
          metadata: Json;
          owner_id: string;
          plan_json: Json | null;
          status: string;
          target_date: string | null;
          title: string;
        };
        Insert: {
          created_at?: string;
          description?: string;
          domain?: string;
          id?: string;
          metadata?: Json;
          owner_id: string;
          plan_json?: Json | null;
          status?: string;
          target_date?: string | null;
          title: string;
        };
        Update: {
          created_at?: string;
          description?: string;
          domain?: string;
          id?: string;
          metadata?: Json;
          owner_id?: string;
          plan_json?: Json | null;
          status?: string;
          target_date?: string | null;
          title?: string;
        };
      };
      jobs: {
        Row: {
          attempts: number;
          created_at: string;
          dedup_key: string | null;
          id: string;
          last_error: string | null;
          payload: Json;
          run_after: string;
          status: string;
          type: string;
        };
        Insert: {
          attempts?: number;
          created_at?: string;
          dedup_key?: string | null;
          id?: string;
          last_error?: string | null;
          payload?: Json;
          run_after?: string;
          status?: string;
          type: string;
        };
        Update: {
          attempts?: number;
          created_at?: string;
          dedup_key?: string | null;
          id?: string;
          last_error?: string | null;
          payload?: Json;
          run_after?: string;
          status?: string;
          type?: string;
        };
      };
      memories: {
        Row: {
          confidence: number;
          content: string;
          created_at: string;
          goal_id: string | null;
          id: string;
          kind: string;
          owner_id: string;
          source: string;
          status: string;
          superseded_by: string | null;
        };
        Insert: {
          confidence?: number;
          content: string;
          created_at?: string;
          goal_id?: string | null;
          id?: string;
          kind: string;
          owner_id: string;
          source?: string;
          status?: string;
          superseded_by?: string | null;
        };
        Update: {
          confidence?: number;
          content?: string;
          created_at?: string;
          goal_id?: string | null;
          id?: string;
          kind?: string;
          owner_id?: string;
          source?: string;
          status?: string;
          superseded_by?: string | null;
        };
      };
      milestone_completions: {
        Row: {
          awarded_xp: number;
          created_at: string;
          decided_by: string;
          id: string;
          milestone_id: string;
          minted_collectible_id: string | null;
          owner_id: string;
          triggering_evidence_ids: string[];
        };
        Insert: {
          awarded_xp?: number;
          created_at?: string;
          decided_by: string;
          id?: string;
          milestone_id: string;
          minted_collectible_id?: string | null;
          owner_id: string;
          triggering_evidence_ids?: string[];
        };
        Update: {
          awarded_xp?: number;
          created_at?: string;
          decided_by?: string;
          id?: string;
          milestone_id?: string;
          minted_collectible_id?: string | null;
          owner_id?: string;
          triggering_evidence_ids?: string[];
        };
      };
      milestones: {
        Row: {
          acceptance_rule: Json;
          completed_at: string | null;
          created_at: string;
          depends_on_id: string | null;
          description: string;
          goal_id: string;
          id: string;
          metadata: Json;
          order_index: number;
          owner_id: string;
          rarity: string;
          status: string;
          title: string;
          xp_reward: number;
        };
        Insert: {
          acceptance_rule?: Json;
          completed_at?: string | null;
          created_at?: string;
          depends_on_id?: string | null;
          description?: string;
          goal_id: string;
          id?: string;
          metadata?: Json;
          order_index?: number;
          owner_id: string;
          rarity?: string;
          status?: string;
          title: string;
          xp_reward?: number;
        };
        Update: {
          acceptance_rule?: Json;
          completed_at?: string | null;
          created_at?: string;
          depends_on_id?: string | null;
          description?: string;
          goal_id?: string;
          id?: string;
          metadata?: Json;
          order_index?: number;
          owner_id?: string;
          rarity?: string;
          status?: string;
          title?: string;
          xp_reward?: number;
        };
      };
      notifications: {
        Row: {
          channels: string[];
          created_at: string;
          dedup_key: string | null;
          id: string;
          owner_id: string;
          persona_msg: string;
          ref_goal_id: string | null;
          ref_milestone_id: string | null;
          scheduled_for: string;
          status: string;
          trigger: string;
        };
        Insert: {
          channels?: string[];
          created_at?: string;
          dedup_key?: string | null;
          id?: string;
          owner_id: string;
          persona_msg?: string;
          ref_goal_id?: string | null;
          ref_milestone_id?: string | null;
          scheduled_for?: string;
          status?: string;
          trigger: string;
        };
        Update: {
          channels?: string[];
          created_at?: string;
          dedup_key?: string | null;
          id?: string;
          owner_id?: string;
          persona_msg?: string;
          ref_goal_id?: string | null;
          ref_milestone_id?: string | null;
          scheduled_for?: string;
          status?: string;
          trigger?: string;
        };
      };
      pets: {
        Row: {
          branch: string;
          goal_id: string;
          id: string;
          mood: number;
          owner_id: string;
          species: string;
          sprite_set: string;
          stage: string;
          updated_at: string;
          xp: number;
        };
        Insert: {
          branch?: string;
          goal_id: string;
          id?: string;
          mood?: number;
          owner_id: string;
          species?: string;
          sprite_set?: string;
          stage?: string;
          updated_at?: string;
          xp?: number;
        };
        Update: {
          branch?: string;
          goal_id?: string;
          id?: string;
          mood?: number;
          owner_id?: string;
          species?: string;
          sprite_set?: string;
          stage?: string;
          updated_at?: string;
          xp?: number;
        };
      };
      subscriptions: {
        Row: {
          expires_at: string | null;
          owner_id: string;
          source: string;
          tier: string;
        };
        Insert: {
          expires_at?: string | null;
          owner_id: string;
          source: string;
          tier?: string;
        };
        Update: {
          expires_at?: string | null;
          owner_id?: string;
          source?: string;
          tier?: string;
        };
      };
    };
    Functions: {
      claim_jobs: {
        Args: { batch?: number };
        Returns: Database["public"]["Tables"]["jobs"]["Row"][];
      };
    };
  };
};
